export SOPS_AGE_KEY_FILE=$HOME/.sops/age-master-key.txt
export EDITOR="micro" # pkgx
export HOMEBREW_NO_ANALYTICS=1
export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
export VIRTUAL_ENV_DISABLE_PROMPT=1 # stop issue where virtualenv was erroneously appearing at the end of every cmd output
export KUBECONFIG="/Users/timothybryant/.kube/config_k3s"
export PATH=$PATH:$HOME/.local/bin/go # pkgx
export GOPATH=$HOME/go
export PATH=$PATH:$HOME/go/bin/
export MICRO_TRUECOLOR=1
export VAULT_ADDR="https://vault.local.timmybtech.com"
export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/opt/postgresql@13/bin:$PATH"
export DOCKER_HOST='unix:///Users/timothybryant/.local/share/containers/podman/machine/qemu/podman.sock'
export PATH="$PATH:$HOME/.config/bin/utilities"
export PYENV_ROOT="$HOME/.pyenv" # homebrew
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$HOME/.basher/bin:$PATH" # source (git)