[[repos]]
path = "automation_ansible"
tags = ["automation_ansible", "homelab", "ansible"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/automation_ansible.git"

[[repos]]
path = "automation_packer"
tags = ["automation_packer", "homelab", "packer"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/automation_packer.git"

[[repos]]
path = "automation_pyinfra"
tags = ["automation_pyinfra", "homelab", "pyinfra"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/automation_pyinfra.git"

[[repos]]
path = "automation_scripts"
tags = ["automation_scripts", "homelab", "scripts"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/automation_scripts.git"

[[repos]]
path = "automation_terraform"
tags = ["automation_terraform", "homelab", "terraform"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/automation_terraform.git"

[[repos]]
path = "cloudflare-timmybtech"
tags = ["cf-timmybtech", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/cloudflare-timmybtech.git"

[[repos]]
path = "cloudflare-timothybryantjr"
tags = ["cf-timothybryantjr", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/cloudflare-timothybryantjr.git"

[[repos]]
path = "docker-apps"
tags = ["docker-apps", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/docker-apps.git"

[[repos]]
path = "dotfiles"
tags = ["dotfiles", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/dotfiles.git"


[[repos]]
path = "dotfiles_linux"
tags = ["dotfiles_linux", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/dotfiles_linux.git"

[[repos]]
path = "kubernetes-apps"
tags = ["kubernetes-apps", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/kubernetes-apps.git"

[[repos]]
path = "oci-timmyb824"
tags = ["oci-timmyb824", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/oci-timmyb824.git"

[[repos]]
path = "timmyb824"
tags = ["timmyb824", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@github.com:timmyb824/timmyb824.git"

[[repos]]
path = "807597f33b14eceeb26e4e6f81d45962"
tags = ["packages", "homelab"]

[repos.remotes.origin]
name = "origin"
url = "git@gist.github.com:807597f33b14eceeb26e4e6f81d45962.git"


